### ISSUE TITLE
Victim is always the killer

### ISSUE THREAD

**Issue by Fank** [OCAP2/addon#2]
![image](https://user-images.githubusercontent.com/1900106/124985294-8809ca00-e03a-11eb-91df-1f6fd28c6a53.png)

http://162.55.178.211:5000/?file=2021_07_08__20_32_opt_v40.json&frame=592&zoom=2.3000000000000003&x=-128&y=128

**Comment by Fank** [comment]
Looks like we are using a modified version of ACE, do you know which module we need to make it work?

**Comment by Fank** [comment]
Looks like we have a modified version of ACE, where those variables are missing

**Comment by Zealot111** [comment]
if should work event without ACE but with lesser accuracy, I will look into the latest implementations
